// apps/solidjs/src/components/Header/Header.tsx
import { Component } from "solid-js";
import styles from "./Header.module.css";
import { useNavigate } from "@solidjs/router";

const Header: Component = () => {
  const nav = useNavigate();
  return (
    <div class={styles.header}>
      <img
        alt="logo"
        src="/icon.png"
        onClick={() => nav("/", { replace: true })}
      />
      <button
        onClick={() => {
          nav("/auth/logout", { replace: true });
        }}
      >
        LOGOUT
      </button>
    </div>
  );
};

export default Header;

// apps/qwik/src/components/Header/Header.tsx
import { component$, useStylesScoped$ } from "@builder.io/qwik";
import styles from "./Header.css?inline";
import { useNavigate } from "@builder.io/qwik-city";
export default component$(() => {
  useStylesScoped$(styles);
  const nav = useNavigate();
  return (
    <div class="header">
      <img alt="logo" src="/icon.png" onClick$={() => nav("/", true)} />
      <button
        onClick$={() => {
          nav("/auth/logout");
        }}
      >
        LOGOUT
      </button>
    </div>
  );
});
