// apps/qwik/src/components/Igredient/Igredient.tsx
import { component$, useStylesScoped$ } from "@builder.io/qwik";
import styles from "./Igredient.css?inline";
import type { IngredientType } from "~/types";

export default component$(({ name, quantity, type }: IngredientType) => {
  useStylesScoped$(styles);
  return (
    <div class="ingredient">
      <h4>
        {name} ({quantity})
      </h4>
      <p>{type}</p>
    </div>
  );
});

// apps/solidjs/src/components/Igredient/Igredient.tsx
import { Component } from "solid-js";
import { IngredientType } from "~/types";
import styles from "./Igredient.module.css";
interface Props {
  ingridient: IngredientType;
}
const Igredient: Component<Props> = ({
  ingridient: { name, type, quantity },
}) => {
  return (
    <div class={styles.ingredient}>
      <h4>
        {name} ({quantity})
      </h4>
      <p>{type}</p>
    </div>
  );
};

export default Igredient;
