// apps/solidjs/src/components/Recipe/Recipe.tsx
import { Component } from "solid-js";
import styles from "./Recipe.module.css";
import { RecipesType } from "~/types";
import { A } from "solid-start";
import { encodeId } from "~/utils";
interface Props {
  recipe: RecipesType;
}
const Recipe: Component<Props> = ({ recipe }) => {
  return (
    <div class={styles.recipe}>
      <h1>{recipe.name}</h1>
      <img src={recipe.imageURL || "/cover.jpg"} alt={recipe.name} />
      <A href={`/recipe/${encodeId(recipe.name)}`}>OPEN</A>
    </div>
  );
};

export default Recipe;

// apps/qwik/src/components/Recipe/Recipe.tsx
import { component$, useStylesScoped$ } from "@builder.io/qwik";

import styles from "./Recipe.css?inline";
import type { RecipesType } from "~/types";
import { Link } from "@builder.io/qwik-city";
import { encodeId } from "~/utils";

interface Props {
  recipe: RecipesType;
}
export default component$((props: Props) => {
  useStylesScoped$(styles);
  return (
    <div class="recipe">
      <h1>{props.recipe.name}</h1>
      <img
        src={props.recipe.imageURL || "/cover.jpg"}
        alt={props.recipe.name}
      />
      <Link href={`/recipe/${encodeId(props.recipe.name)}`}>OPEN</Link>
    </div>
  );
});
