// apps/qwik/src/components/Instruction/Instruction.tsx
import { component$, useStylesScoped$ } from "@builder.io/qwik";
import styles from "./Instruction.css?inline";
export default component$(({ instruction }: { instruction: string }) => {
  useStylesScoped$(styles);
  return (
    <div class="instruction">
      <p>{instruction}</p>
    </div>
  );
});

// apps/solidjs/src/components/Instruction/Instruction.tsx
import { Component } from "solid-js";
import styles from "./Instruction.module.css";

interface Props {
  instruction: string;
}

const Instruction: Component<Props> = ({ instruction }) => {
  return (
    <div class={styles.instruction}>
      <p>{instruction}</p>
    </div>
  );
};

export default Instruction;
