// apps/qwik/src/routes/index.tsx
import {
  component$,
  useSignal,
  useStylesScoped$,
  useVisibleTask$,
} from "@builder.io/qwik";
import type { DocumentHead, RequestHandler } from "@builder.io/qwik-city";
import { routeLoader$ } from "@builder.io/qwik-city";
import Banner from "~/components/Banner/Banner";
import Header from "~/components/Header/Header";
import { TOKEN_KEY } from "~/constants";
import type { MeType, RecipesType } from "~/types";
import styles from "./index.css?inline";
import Recipe from "~/components/Recipe/Recipe";

export const onGet: RequestHandler = async (response) => {
  const token = response.cookie.get(TOKEN_KEY);
  const res = await fetch("http://127.0.0.1:3001/auth/me", {
    headers: {
      Authorization: `Bearer ${token?.value ? token.value : ""}`,
    },
    credentials: "include",
  });
  const { me }: { me: MeType | null } = await res.json();
  if (!me) {
    response.redirect(307, "/auth/login");
  }
};

export const useTokenData = routeLoader$(async (requestContext) => {
  const token = await requestContext.cookie.get(TOKEN_KEY);
  return {
    token: token ? token.value : "",
  };
});
export default component$(() => {
  useStylesScoped$(styles);
  const recipes = useSignal<RecipesType[]>([]);
  const tokenData = useTokenData();

  useVisibleTask$(async () => {
    const token = tokenData.value.token;
    const res = await fetch(`http://127.0.0.1:3001/recipes/recipes`, {
      credentials: "include",
      headers: {
        authorization: `Bearer ${token}`,
      },
    });
    const { recipes: _ }: { recipes: Array<RecipesType> } = await res.json();

    recipes.value = _;
  });

  return (
    <div class="home">
      <Header />
      <Banner />

      <div class="home__recipes">
        <h1>ALL RECIPES</h1>
        <div class="home__recipes__list">
          {recipes.value.map((recipe) => (
            <Recipe key={recipe.name} recipe={recipe} />
          ))}
        </div>
      </div>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Home",
  meta: [
    {
      name: "description",
      content: "Home page",
    },
  ],
};

// apps/solidjs/src/routes/index.tsx
import {
  RouteDataArgs,
  parseCookie,
  useRouteData,
  useServerContext,
} from "solid-start";
import { createServerData$, redirect } from "solid-start/server";
import { REDIRECT_CODES, TOKEN_KEY, storage } from "~/constants";
import { MeType, RecipesType } from "~/types";
import Header from "~/components/Header/Header";
import Banner from "~/components/Banner/Banner";
import styles from "./index.module.css";
import { For, createEffect, on } from "solid-js";
import Recipe from "~/components/Recipe/Recipe";
import { createStore } from "solid-js/store";
export const routeData = () => {
  return createServerData$(async (_, event) => {
    const session = await storage.getSession(
      event.request.headers.get("Cookie") ?? ""
    );
    const token = session.get(TOKEN_KEY) ?? "";
    const res = await event.fetch("http://127.0.0.1:3001/auth/me", {
      headers: {
        Authorization: `Bearer ${token}`,
      },
      credentials: "include",
    });
    const { me }: { me: MeType | null } = await res.json();
    if (!!!me) {
      return redirect("/auth/login", REDIRECT_CODES.TEMPORARY_REDIRECT);
    }
    return {
      me,
      token,
    };
  });
};

export default function Home() {
  const { latest } = useRouteData<typeof routeData>();
  const [recipes, setRecipes] = createStore<Array<RecipesType>>([]);
  createEffect(async () => {
    const res = await fetch("/api/recipes");
    const recipes = await res.json();
    setRecipes(recipes);
  });

  return (
    <div class={styles.home}>
      <Header />
      <Banner />
      <div class={styles.home__recipes}>
        <h1>ALL RECIPES</h1>
        <div class={styles.home__recipes__list}>
          <For each={recipes || []} fallback={<div>Loading...</div>}>
            {(recipe) => <Recipe recipe={recipe} />}
          </For>
        </div>
      </div>
    </div>
  );
}
