// apps/qwik/src/components/Banner/Banner.tsx
import { component$, useStylesScoped$ } from "@builder.io/qwik";
import styles from "./Banner.css?inline";

export default component$(() => {
  useStylesScoped$(styles);
  return (
    <div class="banner">
      <h1>RECIPES APP</h1>
      <p>
        Welcome to our recipes app. Get to explore the recipes that we have in
        our database.
      </p>
    </div>
  );
});

// apps/solidjs/src/components/Banner/Banner.tsx
import { Component } from "solid-js";
import styles from "./Banner.module.css";

const Banner: Component = () => {
  return (
    <div class={styles.banner}>
      <h1>RECIPES APP</h1>
      <p>
        Welcome to our recipes app. Get to explore the recipes that we have in
        our database.
      </p>
    </div>
  );
};
export default Banner;
